# -*- coding: utf-8 -*-
"""telegrambot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cX4leluewAlGIoVVr2jVDsDUzaNqDfiD
"""

import telegram
from telegram import ReplyKeyboardMarkup, ReplyKeyboardRemove, Update, ForceReply, InlineKeyboardMarkup, InlineKeyboardButton
from telegram.ext import (
    Updater,
    CommandHandler,
    MessageHandler,
    Filters,
    ConversationHandler,
    CallbackContext,
)

bot = telegram.Bot(token="token")

content_img = False
style_img = False


def start(update: Update, context: CallbackContext) -> None:
  global content_img, style_img
  user = update.effective_user
  content_img = False
  style_img = False
  # просит пользователя отправить content image
  update.message.reply_text("Send not compressed Content Image")


def image_handler(update: Update, context: CallbackContext) -> None:
    global content_img, style_img
    content = update.message.document.file_id
    img = bot.get_file(content)
    if not content_img:
        # скачиваем content image
        img.download("content.jpg")
        content_img = True
        # говорим, что получили content image
        context.bot.send_message(chat_id=update.effective_chat.id, text="Content Image received!")
        # просит пользователя отправить style image
        update.message.reply_text("Send not compressed Style Image")
    elif not style_img:
        # скачиваем style image
        img.download("style.jpg")
        style_img = True
        # говорим, что получили style image
        context.bot.send_message(chat_id=update.effective_chat.id, text="Style Image received!")
        # само преобразование
        style_transfer("content.jpg", "style.jpg")
        context.bot.send_message(chat_id=update.effective_chat.id, text="Stylized Target Image:")
        # вывод результата
        bot.send_photo(update.message.chat_id, photo=open('stylized.jpg', 'rb'))
        # кнопка /start
        btn = ReplyKeyboardMarkup([['/start']], resize_keyboard=True)
        update.message.reply_text(text="Click start button if you want more", reply_markup=btn)
def main():
    updater = Updater("token")

    dispatcher = updater.dispatcher
    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(MessageHandler(Filters.document, image_handler))
    updater.start_polling()
    updater.idle()


if __name__ == '__main__':
    main()